---
# tasks file for deploy ssh pub key

- name: copy auth keys of user
  template: src=authorized_keys.j2 dest=~/.ssh/authorized_keys owner=ubuntu group=ubuntu mode=0644
  tags: sshkey

- name: copy sshd config
  become: yes
  template: src=sshd_config.j2 dest=/etc/ssh/sshd_config owner=root group=root mode=0644
  tags: sshconfig

- name: addin ip to ufw
  become: yes
  ufw:
    rule: allow
    port: '9122'
    proto: tcp
    src: '{{ item }}'
  with_items:
    - 5.196.171.67
    - 185.117.119.39
  tags: sshconfig

- name: Restart service ssh
  become: yes
  systemd:
    name: sshd
    state: restarted
  tags: sshconfig

- name: enable ufw
  become: yes
  ufw:
    state: enabled
  tags: sshconfig

- name: Restart service ufw
  become: yes
  systemd:
    name: ufw
    state: restarted
  tags: ufwreload