---
# tasks file for deploy ssh pub key

- name: Installing python 3.x
  become: yes
  apt:
    pkg:
      - python3
      - python3-venv
      - python3-pip
      - nginx
    state: latest
    update_cache: true

- name: creat dir
  become: yes
  file:
    path: "{{ item }}"
    recurse: yes
    owner: "ubuntu"
    mode: 0755
    state: directory
  loop:
   - /opt/apps
   - {{ env }}
   - {{ project_dir }}
   - {{ project_dir }}/logs

- name: copy file project
  become: yes
  copy: src={{ item }} dest={{ project_dir }} owner=ubuntu group=ubuntu mode=0644
  with_items:
   - 'app.py'
   - 'config.py'
   - 'requirements.txt'
   - 'apps.ini'
  
- name: create virtualenv
  pip: virtualenv={{ env }} virtualenv_site_packages=yes {% if requirements %}requirements={{ project_homedir }}/{{ requirements }}{% endif %}
- name: Install wheel
  pip:
    name: wheel
    virtualenv: "{{ env }}"
    virtualenv_command: "/usr/bin/python3 -m venv {{ env }}"

- name: install a django
  pip:
    name: ['uwsgi', 'flask']
    virtualenv: "{{ env }}"
    virtualenv_command: "source /opt/apps/app_test/bin/activate"

# - name: activated source of project
#   become: yes
#   shell: "source /opt/apps/app_test/bin/activate"
#   tags: activeenv

# - name: Install wheel
#   pip:
#     name: {{ item }}
#     virtualenv: "/opt/apps/app_test"
#     virtualenv_command: ""
#   with_items:
#    - 'uwsgi'
#    - 'flask'
    