---
# tasks file for deploy nginx python uwsgi flask, files of project and web configs

- name: Installing python and nginx
  become: yes
  apt:
    pkg:
      - python3
      - python3-venv
      - python3-pip
      - nginx
      - libpcre3 
      - libpcre3-dev
    state: latest
    update_cache: true

- name: creat dir
  become: yes
  file:
    path: '{{ item }}'
    recurse: yes
    owner: 'ubuntu'
    mode: 0755
    state: directory
  loop:
   - '/opt/apps'
   - '{{ env }}'
   - '{{ project_dir }}'
   - '{{ project_dir }}/logs'
   - '{{ uwsgi_log }}'

- name: copy file project
  become: yes
  copy: src={{ item }} dest={{ project_dir }} owner={{ sysuser }} group={{ sysgroup }} mode=0644
  with_items:
   - 'app.py'
   - 'config.py'
   - 'requirements.txt'

- name: copy apps.ini param
  become: yes
  template: src=apps.ini.j2 dest={{ project_dir }}/apps.ini owner=ubuntu group=ubuntu mode=0644

- name: touch log file in /var/log/uwsgi
  become: yes
  file: path=/var/log/uwsgi/apps.log state=touch owner={{ sysuser }} group={{ sysgroup }} mode=0644

- name: create virtualenv
  become: yes
  pip: requirements={{ project_dir }}/{{ requirements }} virtualenv={{ env }} virtualenv_command='python3 -m venv'

- name: install a django
  pip:
    name: 
      - uwsgi
      - flask
    virtualenv: "{{ env }}"
    virtualenv_command: 'source {{ project_dir }}/bin/activate'

- name: copy service file in system
  become: yes
  template: src=app.service.j2 dest=/etc/systemd/system/app.service owner=root group=root mode=644

- name: service is running and enabled
  become: yes
  systemd:
    state: started
    name: app
    enabled: yes
    